---
title: "Algoritma KNN"
author: "Rani Ayu Sukmawati-Institut Teknologi Statistika dan Bisnis Muhammadiyah"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    higlight: zenburn
    toc: true
    toc_float:
      collapsed: true
    df_print: paged
bibliography: references.bib
---

```{=html}
<style>
body{
text-align: justify}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Algoritma KNN

# Tahapan Algoritma KNN

# Eksperimen Algoritma KNN

## Library
```{r}
library(caret)
```

```{r}
summary(iris)
```

```{r}
set.seed(300)
#Spliting data as training and test set. Using createDataPartition() function from caret. p is the percentage of data that goes to training. 
indxTrain <- createDataPartition(y = iris$Species,p = 0.75,list = FALSE)
training <- iris[indxTrain,]
testing <- iris[-indxTrain,]

#Checking distibution in original data and partitioned data
```

```{r}
prop.table(table(testing$Species)) * 100
```

```{r}
prop.table(table(iris$Species)) * 100
```

```{r}
trainX <- training[,names(training) != "Species"]
preProcValues <- preProcess(x = trainX,method = c("center", "scale"))
preProcValues
```

```{r}
set.seed(400)
ctrl <- trainControl(method="repeatedcv",repeats = 3) #,classProbs=TRUE,summaryFunction = twoClassSummary)
knnFit <- train(Species ~ ., data = training, method = "knn", trControl = ctrl, preProcess = c("center","scale"), tuneLength = 20)
#Output of kNN fit
knnFit
```

```{r}
#Plotting yields Number of Neighbours Vs accuracy (based on repeated cross validation)
plot(knnFit)
```

```{r}
knnPredict <- predict(knnFit,newdata = testing )
#Get the confusion matrix to see accuracy value and other parameter values
confusionMatrix(knnPredict, testing$Species )
```

```{r}
mean(knnPredict == testing$Species)
```

